services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: password-manager-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=__PUNE_AICI_JWT_SECRET__
      - ENCRYPTION_KEY=__PUNE_AICI_ENCRYPTION_KEY__
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=passwordmanager
    restart: unless-stopped
    networks:
      - password-manager-network
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: password-manager-frontend
    ports:
      - "1532:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - password-manager-network

  postgres:
    image: postgres:15-alpine
    container_name: password-manager-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=passwordmanager
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - password-manager-network

volumes:
  pgdata:

networks:
  password-manager-network:
    driver: bridge
